### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by marksev1** [haraldkubota/orange_pi_gpio#1]
This input and output pins are they digital or analog? Can you choose?

Did you try i2c maybe also?

**Comment by haraldkubota** [comment]
There's no analog as far as I know. I2C is there and works.
I can add an I2C example later. There are cheap AD and DA converters which use I2C. I got one somewhere...

**Comment by marksev1** [comment]
Nice :). Yes please add I2C example. :)

**Comment by haraldkubota** [comment]
Done. As simple-as-possible with PCF8574.
For more complicated I2C chips, you'll need either a driver or a data sheet. The PCF8574 is simple enough to not need it.
